config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :resumes, only:[:index, :new, :create, :destroy]

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/resume.rb
class Resume < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "Tasnim", password:
  "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "Tasnim", password:
  "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
        redirect_to articles_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded"
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been destroyed"
  end

  private
    def resume_params
      params.require(:resume).permit(:name, :attachment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end


  def new
    @user = User.new
  end


  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

  </head>

  <body>
    <div class="container" style="padding-top: 20px"></div>
    <%= yield %>
  </body>
</html>

app/views/resumes/create.html.erb
<h3 align="center">Resumes#create</h3>
<p align="center">Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h3 align="center">Resumes#destroy</h3>
<p align="center">Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
    <%= flash[:notice]  %>
  </div>
<% end %>

<br/>

<%= link_to "New Resume", new_resume_path, class: "btn btn-primary"%>
<br/>
<br/>

<table class="table table-bordered table-striped" align="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th> </th>
    </tr>
  </thead>
  
  <tbody>
    <% @resumes.each do |resume| %>
    
      <tr>
        <td><%= resume.name %></td>
        <td><%= link_to "Download Resume", resume.attachment_url %></td>
        <td><%= button_to "Delete", resume, method: :delete, class: "btn btn-danger", data: {confirm: 'Are you sure?'} %></td>
      </tr>

      <% end %>
  </tbody>
  
</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  <div class="alert alert-error">

    <ul>
      <% @resume.errors.full_message.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<div class="well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" align="center">
      <h2 align="center"><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" align="center">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field" align="center">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field" align="center">
    <%= form.label :login %>
    <%= form.text_field :login, id: :user_login %>
  </div>

  <div class="actions" align="center">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2 align="center">Editing User</h2>

<p align="center"><%= render 'form', user: @user %></p>

<h4 align="center"><%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %></h4>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h2 align="center" style="color: #730E15">Users</h2>

<table align="center" border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4 align="center"><%= link_to 'New User', new_user_path %></h4>

app/views/users/new.html.erb
<h2 align="center">New User</h2>

<%= render 'form', user: @user %>

<h4 align="center"><%= link_to 'Back', users_path %></h4>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p align="center">
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p align="center">
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p align="center">
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<h4 align="center"><%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %></h4>

app/views/welcome/index.html.erb
<h2 align="center">Hello Rails</h2>

<table align="center" border="1">
  <tr><td><h4 align="center"><%= link_to 'My Blog', controller: 'articles' %></h4></td>
  <tr><td><h4 align="center"><%= link_to 'User', controller: 'users' %></h4></td></tr>
</table>